#!/bin/sh
# panel-poke.sh — hand a Karabiner chord to the resident ccc panel server, else run cold.
#
# GENERATED by `ccc panel-server --install` from the package template
# command_center/assets/panel-poke.sh; edit the template, not the installed copy. The
# installer replaces the @…@ placeholders below with shell-quoted values.
#
# Usage: panel-poke.sh park|peek
#
# Protocol (one request file per chord, ownership by atomic rename):
#   1. verb not park|peek -> exit 2. CCC_PANEL_COLD=1 or CCC_PARK_PANEL_TIMEOUT set
#      (per-invocation controls a resident server cannot see) -> cold.
#   2. panel_server.pid = "<pid> <state> <stamp>"; missing, dead pid, or state not
#      ready|busy -> cold.
#   3. write panel_request.<nonce> = "<verb> <nonce> <epoch_s>" (tmp + mv), poll
#      panel_ack.<nonce> ("<status> <epoch>") for one window (8 x 50 ms):
#      shown|busy|stale -> exit 0, failed -> cold.
#   4. no ack -> abandon: mv panel_request.<nonce> -> panel_abandoned.<nonce>.
#      mv won (never claimed) -> cold. mv lost (the server claimed it) -> one more
#      window; failed -> cold; still no ack and the pid is dead -> cold; otherwise
#      exit 0 (a live server wedged after claiming: no panel, never a duplicate).
# "cold" = exec `<ccc> park -g` / `<ccc> peek`. PANEL_POKE_TRACE=1 prints one stderr
# timestamp line right before each cold exec; nothing else is ever logged.

APP_HOME=@APP_HOME@
COLD_CCC=@COLD_CCC@
# @ENV_OVERRIDES@

verb=${1:-}

cold() {
    if [ -n "${PANEL_POKE_TRACE:-}" ]; then
        now=$(perl -MTime::HiRes=time -e 'printf "%.6f", time' 2>/dev/null) || now=$(date +%s)
        printf 'panel-poke: cold %s %s\n' "$verb" "$now" >&2
    fi
    if [ "$verb" = park ]; then
        exec "$COLD_CCC" park -g
    fi
    exec "$COLD_CCC" peek
}

# wait_ack: poll panel_ack.<nonce> for one window; sets $status, returns 0 on an ack.
wait_ack() {
    n=0
    while :; do
        if [ -f "$ack" ]; then
            status=
            read -r status _rest < "$ack" 2>/dev/null
            [ -n "$status" ] && return 0
        fi
        [ "$n" -ge 8 ] && return 1
        sleep 0.05
        n=$((n + 1))
    done
}

# act_on_ack: exit 0 on shown|busy|stale, cold on failed (or anything unknown).
act_on_ack() {
    case $status in
        shown | busy | stale) exit 0 ;;
    esac
    cold
}

case $verb in
    park | peek) ;;
    *)
        printf 'usage: panel-poke.sh park|peek\n' >&2
        exit 2
        ;;
esac

if [ "${CCC_PANEL_COLD:-}" = 1 ] || [ -n "${CCC_PARK_PANEL_TIMEOUT:-}" ]; then
    cold
fi

pidfile=$APP_HOME/panel_server.pid
[ -f "$pidfile" ] || cold
pid=
state=
read -r pid state _stamp < "$pidfile" 2>/dev/null
case $pid in
    '' | *[!0-9]*) cold ;;
esac
kill -0 "$pid" 2>/dev/null || cold
case $state in
    ready | busy) ;;
    *) cold ;;
esac

epoch=$(date +%s)
nonce=$$-$epoch
request=$APP_HOME/panel_request.$nonce
ack=$APP_HOME/panel_ack.$nonce
tmp=$APP_HOME/panel_tmp.$nonce
printf '%s %s %s\n' "$verb" "$nonce" "$epoch" > "$tmp" 2>/dev/null || cold
mv -f "$tmp" "$request" 2>/dev/null || cold

wait_ack && act_on_ack

if mv "$request" "$APP_HOME/panel_abandoned.$nonce" 2>/dev/null; then
    cold  # never claimed: the server is wedged before claiming (or gone)
fi

# The server claimed the request: give it one more window.
wait_ack && act_on_ack
kill -0 "$pid" 2>/dev/null || cold  # crashed after the claim
exit 0
